sudo: required

dist: xenial

os:
  - linux

language: python

python:
  - '3.7'

addons:
  apt:
    packages:
      - xvfb

env:
  global:
    # Doctr deploy key for OpenGeoVis/GeothermalDesignChallenge
    - secure: "O1KfN8j83H1Wyki/+r7y4QySqA6ooGb/fuhP9aA1PaKH3UaDy775BZ+kWlO0oBrlRWhiSsR5i/BhPOVaNSfFL07KfEBystZCJhoStXhjz+rGh3c6MjqjOjsLLto7p4jPGOhgWN2DpC95ahwgE5w7M1VMhXX59E4KWlauuEfx9DaCY3fYoWUuALZDjFz8xpPXO6gYpsAWIDMBqKa2czWJcIjfKI2GsH+mnY8xuby+j8ohEgk1C5f80QCbv+QYLUtN4TIWY3RwJ+QKbGPahYrB0tINnGabjG8LSdwAiXUdmqryrt+/JfgF2D0izOSBsGuZCqlD4ohe94Khck9f1aeuWIiMA+0S0dk5TAOcQw1zDp1h8rH/26FzD4k1MekiwE1jl7xs/XlnflO23cTmYRl1q03AYWlhn/20GWW3UeY7xhb4VMRY/hw47omC/pOIXA6N+IpZp3WaL7+quLan6zhpTICj+w1rHxCWRG63OdIJ8VO46xt2HCFpXPYKcjthPMFhga+PDc/WDYkRJDcPkcCRbrXiQ4F7jzH/19TNJ3v0g7kVueexZNSbgSmHnDRyo+xeuUaHQVWS37pZPFxUCsMGj06NAxV+z5YjkMl/inYzxAsvgdNgoxH2MAJVNGb7mA72qV/6Hhcn+UDm+wVtHt6/4F6FXz75PQo+uSkMuzBSLiM="

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh
  # Set up Python
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - export MPLBACKEND="agg"
  - conda update --yes conda

install:
  - conda install --quiet --yes pip
  - conda install --quiet --yes -c conda-forge "gdal=2.4.2"
  - conda install --quiet --yes dask
  - python -c "import gdal; print(gdal.VersionInfo(''))"
  - pip install -r requirements.txt
  - pip install -U doctr
  - pip install cookiecutter
  - which python
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - pip list

script:
  # And make the documentation
  - cd ./docs/
  # Do not run doc testing on python 2.7
  # Run `make html` before `make doctest` to avoid segfault.
  # Then rerun `make html` to use updated figures from `make doctest`
  - set -e;
  - make html;
  # Run twice to make sure all figures are up to date!
  - make html;
  - cd ..
  - doctr deploy --built-docs ./docs/_build/html .;

cache:
  directories:
  - "$HOME/.cache/pip"


notifications:
  email: false
