name: pyvista-environment
channels:
  - bokeh/label/dev
  - pyviz/label/dev
  - conda-forge
dependencies:
  - python
  - bokeh
  - panel
  - gdal
  - numpy
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - git+git://github.com/OpenGeoVis/PVGeo@master
    - discretize>=0.3.8
    - omfvista>=0.2.0
    - xlrd>=1.1.0
    - lasio
    - pyshp
    - sklearn
    - matplotlib
